project_id = "sldbiucmeottmsybuybq"

[functions.gemini-analyze]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.analyze-plant-health]
verify_jwt = false

[functions.ai-crop-predictions]
verify_jwt = false